# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourmin',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fourmin',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
