# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20170523_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OverDrive',
        ),
        migrations.AlterField(
            model_name='actionbooks',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actionbooks',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cliffnotes',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cliffnotes',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goodreads',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goodreads',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='readitforme',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='readitforme',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sparknotes',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sparknotes',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
