# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20170526_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionBooks',
        ),
        migrations.DeleteModel(
            name='Amazon',
        ),
        migrations.DeleteModel(
            name='CliffNotes',
        ),
        migrations.DeleteModel(
            name='GoodReads',
        ),
        migrations.DeleteModel(
            name='ReadItForMe',
        ),
        migrations.DeleteModel(
            name='SparkNotes',
        ),
        migrations.DeleteModel(
            name='Wiki',
        ),
    ]
