# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20170526_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blink',
            new_name='BlinkMod',
        ),
    ]
