# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
