# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0007_auto_20170526_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMinMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('url', models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FourMin',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='blinkmod',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blinkmod',
            name='url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
