# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0010_auto_20170527_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readitformemod',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
